CREATE TABLE ADMIN_TO_COM (
	A2C_MSG_ID INT AUTO_INCREMENT COMMENT 'A2C 訊息編號',
	A2C_SENDER_ID INT COMMENT '發信管理者編號',
    A2C_RECEIVER_ID INT COMMENT '收件商家編號',
    A2C_SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    A2C_MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    A2C_MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(A2C_MSG_ID)
#   CONSTRAINT FK_A2C_SENDER_ID FOREIGN KEY (A2C_SENDER_ID) REFERENCES ADMIN(ADMIN_ID)
#	CONSTRAINT FK_A2C_RECV_ID FOREIGN KEY (A2C_RECEIVER_ID) REFERENCES COMPANY(COM_ID)
) COMMENT 'A2C 訊息表';


SELECT * FROM ADMIN_TO_COM;

INSERT INTO ADMIN_TO_COM(A2C_MSG_ID,A2C_SENDER_ID,A2C_RECEIVER_ID,A2C_SENDING_TIME,A2C_MSG_TITLE,A2C_MSG_CONTENT)
VALUES(1,1,1,(NOW()),"A商家名稱上架訊息回覆","關於貴公司的上架審核的部分已經通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_COM(A2C_MSG_ID,A2C_SENDER_ID,A2C_RECEIVER_ID,A2C_SENDING_TIME,A2C_MSG_TITLE,A2C_MSG_CONTENT)
VALUES(2,1,3,(NOW()),"B商家帳號註冊審核通過","關於貴公司的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_COM(A2C_MSG_ID,A2C_SENDER_ID,A2C_RECEIVER_ID,A2C_SENDING_TIME,A2C_MSG_TITLE,A2C_MSG_CONTENT)
VALUES(3,1,2,(NOW()),"C商家帳號註冊審核通過","關於貴公司的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_COM(A2C_MSG_ID,A2C_SENDER_ID,A2C_RECEIVER_ID,A2C_SENDING_TIME,A2C_MSG_TITLE,A2C_MSG_CONTENT)
VALUES(4,1,4,(NOW()),"D商家帳號註冊審核通過","關於貴公司的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_COM(A2C_MSG_ID,A2C_SENDER_ID,A2C_RECEIVER_ID,A2C_SENDING_TIME,A2C_MSG_TITLE,A2C_MSG_CONTENT)
VALUES(5,1,6,(NOW()),"E商家帳號註冊審核通過","關於貴公司的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_COM(A2C_MSG_ID,A2C_SENDER_ID,A2C_RECEIVER_ID,A2C_SENDING_TIME,A2C_MSG_TITLE,A2C_MSG_CONTENT)
VALUES(6,1,5,(NOW()),"F商家帳號註冊審核通過","關於貴公司的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

SELECT * FROM ADMIN_TO_COM;
#SELECT COUNT(*) FROM ADMIN_TO_COM;
#select * from ADMIN_TO_COM where A2C_SENDING_TIME BETWEEN '2023-03-28' AND '2023-03-29';
#SELECT * FROM ADMIN_TO_COM ORDER BY A2C_SENDING_TIME DESC;
#SELECT * FROM ADMIN_TO_COM ORDER BY A2C_SENDING_TIME DESC LIMIT 0,5;
#DELETE FROM ADMIN_TO_COM;

#DROP TABLE ADMIN_TO_COM;
