CREATE TABLE ADMIN_TO_USER (
	MSG_ID INT AUTO_INCREMENT COMMENT 'A2U 訊息編號',
	SENDER_ID INT COMMENT '發信管理者編號',
    RECEIVER_ID INT COMMENT '收件會員編號',
    SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(MSG_ID)
#   CONSTRAINT FK_ADMIN_TO_USER_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES ADMIN(ADMIN_ID)
#	CONSTRAINT FK_ADMIN_TO_USER_RECV_ID FOREIGN KEY (RECEIVER_ID) REFERENCES USER(USER_ID)
) COMMENT 'A2U 訊息表';

INSERT INTO ADMIN_TO_USER(MSG_ID,SENDER_ID,RECEIVER_ID,SENDING_TIME,MSG_TITLE,MSG_CONTENT)
VALUES(1,1,10,(NOW()),"A使用者帳號註冊審核通過","XXX先生您好，您的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_USER(MSG_ID,SENDER_ID,RECEIVER_ID,SENDING_TIME,MSG_TITLE,MSG_CONTENT)
VALUES(2,1,20,(NOW()),"B使用者付款問題","XXX先生您好，本平台目前只支援信用卡支付功能，謝謝");

SELECT * FROM ADMIN_TO_USER;

#DELETE FROM ADMIN_TO_USER

#DROP TABLE ADMIN_TO_USER;