DROP TABLE ADMIN_TO_USER;

CREATE TABLE ADMIN_TO_USER (
	A2U_MSG_ID INT AUTO_INCREMENT COMMENT 'A2U 訊息編號',
	A2U_SENDER_ID INT COMMENT '發信管理者編號',
    A2U_RECEIVER_ID INT COMMENT '收件會員編號',
    A2U_SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    A2U_MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    A2U_MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(A2U_MSG_ID)
#   CONSTRAINT FK_A2U_SENDER_ID FOREIGN KEY (A2U_SENDER_ID) REFERENCES ADMIN(ADMIN_ID)
#	CONSTRAINT FK_A2U_RECV_ID FOREIGN KEY (A2U_RECEIVER_ID) REFERENCES USER(USER_ID)
) COMMENT 'A2U 訊息表';


INSERT INTO ADMIN_TO_USER(A2U_MSG_ID, A2U_SENDER_ID, A2U_RECEIVER_ID, A2U_SENDING_TIME, A2U_MSG_TITLE, A2U_MSG_CONTENT)
VALUES(1, 1, 1, "2023-04-24 14:22:32", "房型設備:床位", "該房型目前有單人房與雙人房，目前暫無四人房的空房。");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID, A2U_SENDER_ID, A2U_RECEIVER_ID, A2U_SENDING_TIME, A2U_MSG_TITLE, A2U_MSG_CONTENT)
VALUES(2, 1, 3, "2023-04-28 17:12:55", "付款問題", "您可以在網站上使用信用卡方式進行付款，謝謝!");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID, A2U_SENDER_ID, A2U_RECEIVER_ID, A2U_SENDING_TIME, A2U_MSG_TITLE, A2U_MSG_CONTENT)
VALUES(3, 1, 1, "2023-05-02 13:13:21", "旅館位置", "我們的旅館位於市中心，距離主要景點和交通樞紐僅幾分鐘的步行路程。您可以輕鬆到達周邊的購物區和餐廳。");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID, A2U_SENDER_ID, A2U_RECEIVER_ID, A2U_SENDING_TIME, A2U_MSG_TITLE, A2U_MSG_CONTENT)
VALUES(4, 1, 4, "2023-05-04 09:48:52", "特殊要求", "如果您有特殊要求，例如無煙房、嬰兒床或輪椅使用等，請在預訂過程中提供相關資訊，我們將盡力滿足您的需求。");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID, A2U_SENDER_ID, A2U_RECEIVER_ID, A2U_SENDING_TIME, A2U_MSG_TITLE, A2U_MSG_CONTENT)
VALUES(5, 1, 2, "2023-05-08 19:24:32", "早餐安排", "我們提供美味的早餐供應，您可以在預訂過程中選擇是否需要早餐，或者在入住時與前臺確認。");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID, A2U_SENDER_ID, A2U_RECEIVER_ID, A2U_SENDING_TIME, A2U_MSG_TITLE, A2U_MSG_CONTENT)
VALUES(6, 1, 1, "2023-05-14 15:33:42", "客房服務","我們提供每日客房清潔服務，包括更換床單和毛巾。如需額外的客房服務，請與前臺聯繫，我們將安排相應的服務。");

SELECT * FROM ADMIN_TO_USER;
#SELECT COUNT(*) FROM ADMIN_TO_USER;
#select * from ADMIN_TO_USER where A2U_SENDING_TIME BETWEEN '2023-03-28' AND '2023-03-29';
#SELECT * FROM ADMIN_TO_USER ORDER BY A2U_SENDING_TIME DESC;
#SELECT * FROM ADMIN_TO_USER ORDER BY A2U_SENDING_TIME DESC LIMIT 0,5;

#DELETE FROM ADMIN_TO_USER

#DROP TABLE ADMIN_TO_USER;