CREATE TABLE ADMIN_TO_COM (
	MSG_ID INT AUTO_INCREMENT COMMENT 'A2C 訊息編號',
	SENDER_ID INT COMMENT '發信管理者編號',
    RECEIVER_ID INT COMMENT '收件商家編號',
    SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(MSG_ID)
#   CONSTRAINT FK_ADMIN_TO_COM_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES ADMIN(ADMIN_ID)
#	CONSTRAINT FK_ADMIN_TO_COM_RECV_ID FOREIGN KEY (RECEIVER_ID) REFERENCES COMPANY(COM_ID)
) COMMENT 'A2C 訊息表';

INSERT INTO ADMIN_TO_COM(MSG_ID,SENDER_ID,RECEIVER_ID,SENDING_TIME,MSG_TITLE,MSG_CONTENT)
VALUES(1,1,10,(NOW()),"A商家名稱上架訊息回覆","關於貴公司的上架審核的部分已經通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_COM(MSG_ID,SENDER_ID,RECEIVER_ID,SENDING_TIME,MSG_TITLE,MSG_CONTENT)
VALUES(2,1,20,(NOW()),"B商家帳號註冊審核通過","關於貴公司的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

SELECT * FROM ADMIN_TO_COM;

#DELETE FROM ADMIN_TO_COM;

#DROP TABLE ADMIN_TO_COM;
