CREATE TABLE ADMIN_TO_USER (
	A2U_MSG_ID INT AUTO_INCREMENT COMMENT 'A2U 訊息編號',
	A2U_SENDER_ID INT COMMENT '發信管理者編號',
    A2U_RECEIVER_ID INT COMMENT '收件會員編號',
    A2U_SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    A2U_MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    A2U_MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(A2U_MSG_ID)
#   CONSTRAINT FK_A2U_SENDER_ID FOREIGN KEY (A2U_SENDER_ID) REFERENCES ADMIN(ADMIN_ID)
#	CONSTRAINT FK_A2U_RECV_ID FOREIGN KEY (A2U_RECEIVER_ID) REFERENCES USER(USER_ID)
) COMMENT 'A2U 訊息表';

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID,A2U_SENDER_ID,A2U_RECEIVER_ID,A2U_SENDING_TIME,A2U_MSG_TITLE,A2U_MSG_CONTENT)
VALUES(1,1,10,(NOW()),"A使用者帳號註冊審核通過","XXX先生您好，您的帳號審核已通過，感謝使用本平台，如有疑問請再發送相關訊息通知，謝謝");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID,A2U_SENDER_ID,A2U_RECEIVER_ID,A2U_SENDING_TIME,A2U_MSG_TITLE,A2U_MSG_CONTENT)
VALUES(2,3,20,(NOW()),"B使用者付款問題","XXX先生您好，本平台目前只支援信用卡支付功能，謝謝");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID,A2U_SENDER_ID,A2U_RECEIVER_ID,A2U_SENDING_TIME,A2U_MSG_TITLE,A2U_MSG_CONTENT)
VALUES(3,2,20,(NOW()),"B使用者付款問題","XXX先生您好，本平台目前只支援信用卡支付功能，謝謝");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID,A2U_SENDER_ID,A2U_RECEIVER_ID,A2U_SENDING_TIME,A2U_MSG_TITLE,A2U_MSG_CONTENT)
VALUES(4,5,20,(NOW()),"B使用者付款問題","XXX先生您好，本平台目前只支援信用卡支付功能，謝謝");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID,A2U_SENDER_ID,A2U_RECEIVER_ID,A2U_SENDING_TIME,A2U_MSG_TITLE,A2U_MSG_CONTENT)
VALUES(5,4,20,(NOW()),"B使用者付款問題","XXX先生您好，本平台目前只支援信用卡支付功能，謝謝");

INSERT INTO ADMIN_TO_USER(A2U_MSG_ID,A2U_SENDER_ID,A2U_RECEIVER_ID,A2U_SENDING_TIME,A2U_MSG_TITLE,A2U_MSG_CONTENT)
VALUES(6,6,20,(NOW()),"B使用者付款問題","XXX先生您好，本平台目前只支援信用卡支付功能，謝謝");


SELECT * FROM ADMIN_TO_USER;
#SELECT COUNT(*) FROM ADMIN_TO_USER;
#select * from ADMIN_TO_USER where A2U_SENDING_TIME BETWEEN '2023-03-28' AND '2023-03-29';
#SELECT * FROM ADMIN_TO_USER ORDER BY A2U_SENDING_TIME DESC;
#SELECT * FROM ADMIN_TO_USER ORDER BY A2U_SENDING_TIME DESC LIMIT 0,5;

#DELETE FROM ADMIN_TO_USER

#DROP TABLE ADMIN_TO_USER;