CREATE TABLE `ARTICLE_COMMENT` (
  `COMMENT_NO` int NOT NULL AUTO_INCREMENT COMMENT '留言編號',
  `POST_ID` int NOT NULL COMMENT '文章編號',
  `USER_ID` int NOT NULL COMMENT '會員編號',
  `COMMENT_CONTENT` varchar(50) NOT NULL COMMENT '留言內容',
  `COMMENT_DATETIME` datetime NOT NULL DEFAULT (now()) COMMENT '留言時間',
  PRIMARY KEY (`COMMENT_NO`),
  KEY `ARTICLE_COMMENT_FK_POST_ID` (`POST_ID`),
  KEY `ARTICLE_COMMENT_FK_USER_ID` (`USER_ID`),
  CONSTRAINT `ARTICLE_COMMENT_FK_POST_ID` FOREIGN KEY (`POST_ID`) REFERENCES `BLOG` (`POST_ID`),
  CONSTRAINT `ARTICLE_COMMENT_FK_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `MEMBER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章留言';
