CREATE TABLE `ARTICLE_TAG` (
  `ARTICLE_TAG_NO` int NOT NULL AUTO_INCREMENT COMMENT '文章標籤編號',
  `POST_ID` int NOT NULL COMMENT '文章編號',
  `TAG_ID` int NOT NULL COMMENT '標籤編號',
  PRIMARY KEY (`ARTICLE_TAG_NO`)
  -- KEY `ARTIVLE_TAG_FK_POST_ID` (`POST_ID`),
  -- KEY `ARTIVLE_TAG_FK_TAG_ID` (`TAG_ID`),
  -- CONSTRAINT `ARTIVLE_TAG_FK_POST_ID` FOREIGN KEY (`POST_ID`) REFERENCES `BLOG` (`POST_ID`),
  -- CONSTRAINT `ARTIVLE_TAG_FK_TAG_ID` FOREIGN KEY (`TAG_ID`) REFERENCES `TAGS` (`TAG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章標籤';

INSERT INTO `ARTICLE_TAG`
(`POST_ID`,`TAG_ID`)
VALUES
(1,1),(1,2),(2,1);