DROP TABLE IF EXISTS  `article_tag`;
CREATE TABLE `article_tag` (
  `ARTICLE_TAG_NO` int NOT NULL AUTO_INCREMENT COMMENT '文章標籤編號',
  `POST_ID` int NOT NULL COMMENT '文章編號',
  `TAG_ID` int NOT NULL COMMENT '標籤編號',
  PRIMARY KEY (`ARTICLE_TAG_NO`)
) COMMENT='文章標籤';

INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (10,1,9);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (11,1,10);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (12,1,11);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (13,1,12);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (20,2,13);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (21,3,14);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (22,3,15);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (23,3,16);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (24,4,17);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (25,4,18);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (26,5,17);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (27,5,19);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (28,6,20);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (29,6,17);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (30,6,21);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (31,6,22);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (32,7,23);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (33,7,24);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (34,7,25);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (35,7,21);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (36,7,17);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (37,8,17);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (38,8,26);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (39,8,27);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (40,13,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (44,2,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (45,3,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (46,9,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (48,7,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (49,6,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (50,4,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (51,5,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (52,15,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (53,16,7);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (54,16,29);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (55,16,30);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (56,16,31);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (57,15,32);
INSERT INTO `article_tag` (`ARTICLE_TAG_NO`,`POST_ID`,`TAG_ID`) VALUES (58,15,14);
