CREATE TABLE ORDER_DETAIL
(
    ORDER_ID        INT         NOT NULL COMMENT '訂單編號' AUTO_INCREMENT,
    USER_ID         INT         NOT NULL COMMENT '消費者編號',
    ROOM_ID         INT         NOT NULL COMMENT '房型編號',
    JOURNEY_ID      INT         NOT NULL COMMENT '私房行程編號',
    ORDER_DATETIME  DATETIME    NOT NULL COMMENT '訂單建立日期' DEFAULT (NOW()),
    ORDER_AMOUNT    INT         NOT NULL COMMENT '訂單總金額',
    ORDER_CHECK_IN  DATE        NOT NULL COMMENT '訂單入住日期',
    ORDER_CHECK_OUT DATE        NOT NULL COMMENT '訂單退房日期',
    ORDER_RANK      TINYINT(5)  NOT NULL COMMENT '訂單評價星等',
    ORDER_COMMENT   VARCHAR(50) NOT NULL COMMENT '訂單評語',
    PRIMARY KEY (ORDER_ID)
#     CONSTRAINT FK_ORDER_DETAIL_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
#     CONSTRAINT FK_ORDER_DETAIL_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID),
#     CONSTRAINT FK_ORDER_DETAIL_JOURNEY_ID FOREIGN KEY (JOURNEY_ID) REFERENCES JOURNEY (JOURNEY_ID)
) COMMENT '訂房訂單資料表';

INSERT INTO ORDER_DETAIL(USER_ID, ROOM_ID, JOURNEY_ID, ORDER_AMOUNT, ORDER_CHECK_IN, ORDER_CHECK_OUT, ORDER_RANK,
                         ORDER_COMMENT)
VALUES (1, 1, 4, 18000, '2023-05-10', '2023-05-15', 5,
        '很棒棒很棒棒很棒棒很棒棒很棒棒很棒棒很棒棒很棒棒很棒棒很棒棒很棒棒');
INSERT INTO ORDER_DETAIL(USER_ID, ROOM_ID, JOURNEY_ID, ORDER_AMOUNT, ORDER_CHECK_IN, ORDER_CHECK_OUT, ORDER_RANK,
                         ORDER_COMMENT)
VALUES (5, 2, 4, 18000, '2023-05-10', '2023-05-15', 1,
        '很爛很爛很爛很爛很爛很爛很爛很爛很爛很爛很爛很爛');
INSERT INTO ORDER_DETAIL(USER_ID, ROOM_ID, JOURNEY_ID, ORDER_AMOUNT, ORDER_CHECK_IN, ORDER_CHECK_OUT, ORDER_RANK,
                         ORDER_COMMENT)
VALUES (10, 3, 4, 18000, '2023-05-10', '2023-05-15', 3,
        '很普通很普通很普通很普通很普通很普通很普通很普通很普通');
INSERT INTO ORDER_DETAIL(USER_ID, ROOM_ID, JOURNEY_ID, ORDER_AMOUNT, ORDER_CHECK_IN, ORDER_CHECK_OUT, ORDER_RANK,
                         ORDER_COMMENT)
VALUES (14, 4, 4, 18000, '2023-05-10', '2023-05-15', 4,
        'testtesttesttesttesttesttesttesttesttesttest');
INSERT INTO ORDER_DETAIL(USER_ID, ROOM_ID, JOURNEY_ID, ORDER_AMOUNT, ORDER_CHECK_IN, ORDER_CHECK_OUT, ORDER_RANK,
                         ORDER_COMMENT)
VALUES (23, 5, 4, 18000, '2023-05-10', '2023-05-15', 2,
        '兩顆星兩顆星兩顆星兩顆星兩顆星兩顆星兩顆星兩顆星兩顆星兩顆星兩顆星');

SELECT *
FROM ORDER_DETAIL;

SELECT *
FROM ROOM;