DROP TABLE COM_TO_ADMIN;

CREATE TABLE COM_TO_ADMIN (
	C2A_MSG_ID INT AUTO_INCREMENT COMMENT 'C2A 訊息編號',
	C2A_SENDER_ID INT COMMENT '發信商家編號',
    C2A_RECEIVER_ID INT COMMENT '收件平台編號',
    C2A_SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    C2A_MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    C2A_MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(C2A_MSG_ID)
#   CONSTRAINT FK_C2A_SENDER_ID FOREIGN KEY (C2A_SENDER_ID) REFERENCES COMPANY(COM_ID)
#	CONSTRAINT FK_C2A_RECV_ID FOREIGN KEY (C2A_RECEIVER_ID) REFERENCES ADMIN(ADMIN_ID)
) COMMENT 'C2A 訊息表';

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(1, 1, 1, "2023-04-22 11:22:12", "房源狀態更新", "感謝您通知我們房源的狀態更新。我們會盡快審核並更新相應的信息。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(2, 3, 1, "2023-04-26 13:21:43", "價格和可用性更新", "感謝您提供最新的價格和可用性信息。我們會儘快更新平台上的房源信息，以確保客戶獲取準確的數據。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(3, 3, 1, "2023-04-29 16:07:08", "促銷和特價優惠", "我們很高興聽到您提供的促銷和特價優惠。請提供相關詳細信息，我們將盡快在平台上宣傳和推廣。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(4, 2, 1, "2023-05-06 12:17:53", "預訂管理和變更", "如果客戶要求預訂變更，請提供相關詳細信息，我們將協助處理並通知客戶相應的變更。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(5, 3, 1, "2023-05-12 19:21:23", "取消政策和退款問題", "如果客戶要求取消預訂並退款，請提供您的取消政策和相應的退款流程，我們將根據政策進行處理。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(6, 2, 1, "2023-05-17 09:43:56", "評價和回饋管理", "感謝您的回饋。我們將審閱評價並採取必要的行動。如有需要，我們也會回覆客戶的評價。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(7, 3, 1, "2023-05-20 16:44:41", "支付和結算問題", "如果您有關於支付和結算的問題，請提供詳細信息，我們的財務團隊將盡快處理並解答您的疑問。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(8, 4, 1, "2023-05-21 09:55:09", "評價和回饋管理", "感謝您的回饋。我們將審閱評價並採取必要的行動。如有需要，我們也會回覆客戶的評價。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(9, 1, 1, "2023-05-25 11:23:49", "房源可見性和排名", "我們會定期優化房源可見性和排名。請提供更多相關信息，以便我們進一步改進您的房源在平台上的展示。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(10, 2, 1, "2023-06-01 12:45:39", "違規舉報和糾紛處理", "如果您有違規舉報或糾紛處理的需求，請提供詳細情況和相關證據，我們將進行調查並儘快解決問題。");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID, C2A_SENDER_ID, C2A_RECEIVER_ID, C2A_SENDING_TIME, C2A_MSG_TITLE, C2A_MSG_CONTENT)
VALUES(11, 3, 1, "2023-06-06 17:11:59", "商家支援和培訓", "如有任何商家支援和培訓的需求，請與我們的支援團隊聯繫，我們將提供所需的幫助和指導。");


SELECT * FROM COM_TO_ADMIN;
#SELECT COUNT(*) FROM COM_TO_ADMIN;
#select * from COM_TO_ADMIN where C2A_SENDING_TIME BETWEEN '2023-03-28' AND '2023-03-29';
#SELECT * FROM COM_TO_ADMIN ORDER BY C2A_SENDING_TIME DESC;
#SELECT * FROM COM_TO_ADMIN ORDER BY C2A_SENDING_TIME DESC LIMIT 0,5;
#DELETE FROM COM_TO_ADMIN;

