CREATE TABLE COM_TO_ADMIN (
	C2A_MSG_ID INT AUTO_INCREMENT COMMENT 'C2A 訊息編號',
	C2A_SENDER_ID INT COMMENT '發信商家編號',
    C2A_RECEIVER_ID INT COMMENT '收件平台編號',
    C2A_SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    C2A_MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    C2A_MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(C2A_MSG_ID)
#   CONSTRAINT FK_C2A_SENDER_ID FOREIGN KEY (C2A_SENDER_ID) REFERENCES COMPANY(COM_ID)
#	CONSTRAINT FK_C2A_RECV_ID FOREIGN KEY (C2A_RECEIVER_ID) REFERENCES ADMIN(ADMIN_ID)
) COMMENT 'C2A 訊息表';

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID,C2A_SENDER_ID,C2A_RECEIVER_ID,C2A_SENDING_TIME,C2A_MSG_TITLE,C2A_MSG_CONTENT)
VALUES(1,1,1,(NOW()),"帳號註冊的審核1","1您好，關於本公司的帳號審核已經過了2天沒有受理，請幫忙看下是否漏掉了");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID,C2A_SENDER_ID,C2A_RECEIVER_ID,C2A_SENDING_TIME,C2A_MSG_TITLE,C2A_MSG_CONTENT)
VALUES(2,2,1,(NOW()),"帳號註冊的審核2","2您好，關於本公司的帳號審核已經過了2天沒有受理，請幫忙看下是否漏掉了");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID,C2A_SENDER_ID,C2A_RECEIVER_ID,C2A_SENDING_TIME,C2A_MSG_TITLE,C2A_MSG_CONTENT)
VALUES(3,3,1,(NOW()),"帳號註冊的審核3","3您好，關於本公司的帳號審核已經過了2天沒有受理，請幫忙看下是否漏掉了");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID,C2A_SENDER_ID,C2A_RECEIVER_ID,C2A_SENDING_TIME,C2A_MSG_TITLE,C2A_MSG_CONTENT)
VALUES(4,4,1,(NOW()),"帳號註冊的審核4","4您好，關於本公司的帳號審核已經過了2天沒有受理，請幫忙看下是否漏掉了");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID,C2A_SENDER_ID,C2A_RECEIVER_ID,C2A_SENDING_TIME,C2A_MSG_TITLE,C2A_MSG_CONTENT)
VALUES(5,5,1,(NOW()),"帳號註冊的審核5","5您好，關於本公司的帳號審核已經過了2天沒有受理，請幫忙看下是否漏掉了");

INSERT INTO COM_TO_ADMIN(C2A_MSG_ID,C2A_SENDER_ID,C2A_RECEIVER_ID,C2A_SENDING_TIME,C2A_MSG_TITLE,C2A_MSG_CONTENT)
VALUES(6,6,1,(NOW()),"帳號註冊的審核6","6您好，關於本公司的帳號審核已經過了2天沒有受理，請幫忙看下是否漏掉了");


SELECT * FROM COM_TO_ADMIN;
#SELECT COUNT(*) FROM COM_TO_ADMIN;
#select * from COM_TO_ADMIN where C2A_SENDING_TIME BETWEEN '2023-03-28' AND '2023-03-29';
#SELECT * FROM COM_TO_ADMIN ORDER BY C2A_SENDING_TIME DESC;
#SELECT * FROM COM_TO_ADMIN ORDER BY C2A_SENDING_TIME DESC LIMIT 0,5;
#DELETE FROM COM_TO_ADMIN;

#DROP TABLE COM_TO_ADMIN;