CREATE TABLE COMPANY
(
    COM_ID        INT         NOT NULL COMMENT '商家編號' AUTO_INCREMENT,
    COM_ACCOUNT   VARCHAR(50) NOT NULL COMMENT '商家帳號',
    COM_PASSWORD  VARCHAR(50) NOT NULL COMMENT '商家密碼',
    COM_NAME      VARCHAR(50) NOT NULL COMMENT '商家名稱',
    COM_ADDRESS   VARCHAR(50) NOT NULL COMMENT '商家地址',
    COM_MANAGER   VARCHAR(50) NOT NULL COMMENT '商家負責人',
    COM_PHONE     CHAR(10)    NOT NULL COMMENT '商家聯絡電話',
    COM_TAXID     VARCHAR(30) NOT NULL COMMENT '統一編號',
    COM_SIGNDATE  DATETIME    NOT NULL COMMENT '商價註冊時間' DEFAULT (NOW()),
    COM_EMAIL     VARCHAR(50) NOT NULL COMMENT '商家信箱',
    COM_STATUS    TINYINT(1)  NOT NULL COMMENT '商家狀態',
    COM_LONGITUDE VARCHAR(10) NOT NULL COMMENT '商家經度',
    COM_LATITUDE  VARCHAR(10) NOT NULL COMMENT '商家緯度',
    COM_AVATAR    LONGBLOB COMMENT '商家頭像',
    PRIMARY KEY (COM_ID),
    UNIQUE KEY UK_COMPANY_COM_ACCOUNT (COM_ACCOUNT)
) COMMENT '商家資料表';





