CREATE TABLE `CREDIT_CARD` (
  `CARD_ID` 	INT 		NOT NULL COMMENT '信用卡資訊編號' AUTO_INCREMENT,
  `USER_ID` 	INT 		NOT NULL COMMENT '會員編號',
  `CARD_NUMBER` CHAR(16) 	NOT NULL COMMENT '信用卡卡號',
  PRIMARY KEY (`CARD_ID`)
# CONSTRAINT FK_CREDIT_CARD_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
) COMMENT '信用卡資訊';
