CREATE TABLE `FAVORITE_ARTICLE` (
  `FAVORITE_ARTICLE` int NOT NULL AUTO_INCREMENT COMMENT '文章收藏編號',
  `USER_ID` int DEFAULT NULL COMMENT '會員編號',
  `POST_ID` int NOT NULL COMMENT '文章編號',
  PRIMARY KEY (`FAVORITE_ARTICLE`),
  KEY `FAVORITE_ARTICLE_FK_USER_ID` (`USER_ID`),
  KEY `FAVORITE_ARTICLE_FK_POST_ID` (`POST_ID`),
  CONSTRAINT `FAVORITE_ARTICLE_FK_POST_ID` FOREIGN KEY (`POST_ID`) REFERENCES `BLOG` (`POST_ID`),
  CONSTRAINT `FAVORITE_ARTICLE_FK_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `MEMBER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章收藏';