# 土產訂單 table
CREATE TABLE `gift_order` (
  `GIFT_ORDER_ID` int NOT NULL AUTO_INCREMENT COMMENT '土產訂單編號',
  `USER_ID` int NOT NULL COMMENT '會員編號',
  `GIFT_ORDER_AMOUNT` int unsigned DEFAULT NULL COMMENT '總金額',
  `GIFT_ORDER_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下訂時間',
  `GIFT_ORDER_TAKETYPE` tinyint(1) NOT NULL COMMENT '取貨方式',
  `GIFT_ORDER_RECEIVER` varchar(30) DEFAULT NULL COMMENT '收件人',
  `GIFT_ORDER_RECEIVE_ADDRESS` varchar(50) DEFAULT NULL COMMENT '收件地址',
  `GIFT_ORDER_CELLPHONE` char(10) DEFAULT NULL COMMENT '聯絡電話',
  `GIFT_ORDER_STATUS` tinyint(1) DEFAULT NULL COMMENT '訂單狀態',
  PRIMARY KEY (`GIFT_ORDER_ID`)
  # constraint FK_GIFT_ORDER_USER_ID foreign key (USER_ID) references MEMBER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='土產訂單';

