CREATE TABLE JOURNEY
(
    JOURNEY_ID     INT         NOT NULL COMMENT '私房行程編號' AUTO_INCREMENT,
    COM_ID         INT         NOT NULL COMMENT '商家編號',
    JOURNEY_NAME   VARCHAR(30) NOT NULL COMMENT '私房行程名稱',
    JOURNEY_PRICE  INT         NOT NULL COMMENT '私房行程價格',
    JOURNEY_DESC   VARCHAR(50) NOT NULL COMMENT '私房行程描述',
    JOURNEY_PIC    LONGBLOB 			COMMENT '私房行程照片',
    JOURNEY_STATUS TINYINT(1)  NOT NULL COMMENT '私房行程狀態',
    PRIMARY KEY (JOURNEY_ID)
#     CONSTRAINT FK_JOURNEY_COM_ID FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
) COMMENT '私房行程資料表';