CREATE TABLE ROOM_PIC
(
    ROOM_PIC_ID INT NOT NULL COMMENT '房型照片編號' AUTO_INCREMENT,
    ROOM_ID     INT NOT NULL COMMENT '房型編號',
    ROOM_PIC    LONGBLOB COMMENT '房型照片',
    PRIMARY KEY (ROOM_PIC_ID)
#     CONSTRAINT FK_ROOM_PIC_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID)
) COMMENT '房型照片資料表';

INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (1, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (1, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (1, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (1, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (1, NULL);

INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (2, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (2, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (2, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (2, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (2, NULL);

INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (3, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (3, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (3, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (3, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (3, NULL);

INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (4, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (4, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (4, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (4, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (4, NULL);

INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (5, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (5, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (5, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (5, NULL);
INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (5, NULL);

SELECT *
FROM ROOM_PIC;