USE PROJECT5;

SELECT ROOM.ROOM_ID, ROOM.ROOM_NAME, RP.ROOM_PIC
FROM ROOM
         JOIN ROOM_PIC RP
              ON ROOM.ROOM_ID = RP.ROOM_ID;

SELECT *
FROM ROOM_PIC;

INSERT INTO ROOM_PIC(ROOM_ID, ROOM_PIC)
VALUES (4, LOAD_FILE('C:/Users/Tibame_T14/Desktop/test/1.png'));

DELETE
FROM ROOM_PIC
WHERE ROOM_PIC_ID = 20;
