CREATE TABLE USER_TO_ADMIN (
	U2A_MSG_ID INT AUTO_INCREMENT COMMENT 'U2A 訊息編號',
	U2A_SENDER_ID INT COMMENT '發信會員編號',
    U2A_RECEIVER_ID INT COMMENT '收件平台編號',
    U2A_SENDING_TIME DATETIME NOT NULL DEFAULT (NOW()) COMMENT '訊息發送時間',
    U2A_MSG_TITLE VARCHAR(50) NOT NULL COMMENT '訊息標題',
    U2A_MSG_CONTENT VARCHAR(1000) NOT NULL COMMENT '訊息內容',
    PRIMARY KEY(U2A_MSG_ID)
#   CONSTRAINT FK_U2A_SENDER_ID FOREIGN KEY (U2A_SENDER_ID) REFERENCES USER(USER_ID)
#	CONSTRAINT FK_U2A_RECV_ID FOREIGN KEY (U2A_RECEIVER_ID) REFERENCES ADMIN(ADMIN_ID)
) COMMENT 'U2A 訊息表';


INSERT INTO USER_TO_ADMIN(U2A_MSG_ID,U2A_SENDER_ID,U2A_RECEIVER_ID,U2A_SENDING_TIME,U2A_MSG_TITLE,U2A_MSG_CONTENT)
VALUES(1,1,1,(NOW()),"帳號註冊的審核","你好，關於本人的帳號審核已經過了2天沒有受理，請在幫忙確認一下");
INSERT INTO USER_TO_ADMIN(U2A_MSG_ID,U2A_SENDER_ID,U2A_RECEIVER_ID,U2A_SENDING_TIME,U2A_MSG_TITLE,U2A_MSG_CONTENT)
VALUES(2,2,1,(NOW()),"促銷活動","你好，想請問六月的時候有哪些土產是有打折的?");
INSERT INTO USER_TO_ADMIN(U2A_MSG_ID,U2A_SENDER_ID,U2A_RECEIVER_ID,U2A_SENDING_TIME,U2A_MSG_TITLE,U2A_MSG_CONTENT)
VALUES(3,2,1,(NOW()),"促銷活動","你好，想請問六月的時候有哪些土產是有打折的?");
INSERT INTO USER_TO_ADMIN(U2A_MSG_ID,U2A_SENDER_ID,U2A_RECEIVER_ID,U2A_SENDING_TIME,U2A_MSG_TITLE,U2A_MSG_CONTENT)
VALUES(4,3,1,(NOW()),"促銷活動","你好，想請問六月的時候有哪些土產是有打折的?");
INSERT INTO USER_TO_ADMIN(U2A_MSG_ID,U2A_SENDER_ID,U2A_RECEIVER_ID,U2A_SENDING_TIME,U2A_MSG_TITLE,U2A_MSG_CONTENT)
VALUES(5,6,1,(NOW()),"促銷活動","你好，想請問六月的時候有哪些土產是有打折的?");
INSERT INTO USER_TO_ADMIN(U2A_MSG_ID,U2A_SENDER_ID,U2A_RECEIVER_ID,U2A_SENDING_TIME,U2A_MSG_TITLE,U2A_MSG_CONTENT)
VALUES(6,4,1,(NOW()),"促銷活動","你好，想請問六月的時候有哪些土產是有打折的?");

SELECT * FROM USER_TO_ADMIN;
#SELECT COUNT(*) FROM USER_TO_ADMIN;
#select * from USER_TO_ADMIN where U2A_SENDING_TIME BETWEEN '2023-03-28' AND '2023-03-29';
#SELECT * FROM USER_TO_ADMIN ORDER BY U2A_SENDING_TIME DESC;
#SELECT * FROM USER_TO_ADMIN ORDER BY U2A_SENDING_TIME DESC LIMIT 0,5;

#DELETE FROM USER_TO_ADMIN;

#DROP TABLE USER_TO_ADMIN;