DROP VIEW VIEW_C2A_MSG;

CREATE VIEW VIEW_C2A_MSG AS SELECT c2a.*, c.*, a.*
FROM COM_TO_ADMIN c2a left join COMPANY c
	on c2a.C2A_SENDER_ID = c.COM_ID
		left join ADMIN a on a.ADMIN_ID = c2a.C2A_RECEIVER_ID;

