DROP VIEW VIEW_A2C_MSG;

CREATE VIEW VIEW_A2C_MSG AS SELECT a2c.*, a.*, c.*
FROM ADMIN_TO_COM a2c left join ADMIN a 
		on a2c.A2C_SENDER_ID = a.ADMIN_ID left join COMPANY c 
        on a2c.A2C_RECEIVER_ID = c.COM_ID;
