CREATE TABLE FAVORITE_COM
(
    FAVORITE_ID INT NOT NULL COMMENT '商家收藏編號' AUTO_INCREMENT,
    USER_ID     INT NOT NULL COMMENT '消費者編號',
    COM_ID      INT NOT NULL COMMENT '商家編號',
    PRIMARY KEY (FAVORITE_ID)
#     CONSTRAINT FK_FAVORITE_COM_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
#     CONSTRAINT FK_FAVORITE_COM_COM_ID FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
) COMMENT '商家收藏資料表'