CREATE TABLE PUBLIC_SCENE (
	SCENE_ID INT AUTO_INCREMENT COMMENT '大眾景點編號',
	ADMIN_ID INT COMMENT '管理者編號',
    SCENE_NAME VARCHAR(30) NOT NULL COMMENT '大眾景點名稱',
    SCENE_PHTOT LONGBLOB COMMENT '大眾景點照片',
    SCENE_DESC VARCHAR(1000) NOT NULL COMMENT '大眾景點描述',
    SCENE_ADDR VARCHAR(150) NOT NULL COMMENT '大眾景點地址',
    SCENE_LAT VARCHAR(50) NOT NULL COMMENT '大眾景點緯度',
    SCENE_LNG VARCHAR(50) NOT NULL COMMENT '大眾景點經度',
    PRIMARY KEY(SCENE_ID)
#   CONSTRAINT FK_PUBLIC_SCENE_ID FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
) COMMENT '大眾景點表';

INSERT INTO PUBLIC_SCENE(SCENE_ID,ADMIN_ID,SCENE_NAME,SCENE_PHTOT,SCENE_DESC,SCENE_ADDR,SCENE_LAT,SCENE_LNG)
VALUES(1,1,"幾米公園",NULL,"「幾米主題廣場」位於宜蘭火車站南側，原為廢棄的鐵路局舊宿舍區，後經過重新規劃整建，除了保留原有的歷史建築與老樹綠蔭外，更以「記憶片刻風景」為主題，置入取自知名繪本作家「幾米」的場景所製成的裝置藝術，包含「向左走‧向右走」、「星空」…等繪本中的著名場景，都在此原貌重現。不但已成為拍照的著名場景，更是全台第一座幾米主題廣場。",
"260宜蘭縣宜蘭市宜興路一段240號","24.752733529527834", "121.75705744620144");

SELECT * FROM PUBLIC_SCENE;
#DROP TABLE PUBLIC_SCENE;
#DELETE FROM PUBLIC_SCENE;